language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tempDockerReact -f Dockerfile.dev Dockerfile.dev .

script:
  - docker run -e CI=true tempDockerReact npm run test
